# Generated by Django 4.2.11 on 2025-09-06 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filmwork',
            name='file_path',
        ),
    ]
